name: Testing the GitHub Pages publication

on:
  push

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Use GitHub Actions' cache to shorten build times and decrease load on servers
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    # Standard usage
#    - uses:  helaili/jekyll-action@v2
#      with:
#        token: ${{ secrets.GITHUB_TOKEN }}

#    - name: 🧪 Build and deploy
#      uses: victoriadrake/jekyll-cd@master

#    - name: Build & Deploy to GitHub Pages
#      uses: BryanSchuetz/jekyll-deploy-gh-pages@master
#      env: 
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
#        GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}

    # Specify the Jekyll source location as a parameter
#    - uses: helaili/jekyll-action@v2
#      with:
#        token: ${{ secrets.GITHUB_TOKEN }}
#        jekyll_src: '.'

#    # Specify the target branch (optional)
#    - uses: helaili/jekyll-action@v2
#      with:
#        token: ${{ secrets.GITHUB_TOKEN }}
#        target_branch: 'gh-pages'

#    - name: Build & Deploy to GitHub Pages
#      uses: joshlarsen/jekyll4-deploy-gh-pages@master
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
#        GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}





#    - name: Deploy Jekyll Site
#      uses: sujaykundu777/jekyll-deploy-action@1.0.3
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
#        GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}        



    - uses: EdricChan03/action-build-deploy-ghpages@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }} # Or ${{ github.token }}
        # gh_pages_token: ${{ secrets.GH_PAGES_TOKEN }}
